johnslist/main/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from main import views

urlpatterns = [
    #user urls
    url(r'^user/?$', views.user_dash,name='user_dash'),
    url(r'^user/create/(?P<profile>[a-z]+)/?$', views.user_create,name='user_create'),
    url(r'^user/(?P<user_id>[0-9]+)/user_membership/?$', views.user_membership,name='user_membership'),
    url(r'^user/edit/?$', views.user_settings,name='user_settings'),
    #organization urls
    url(r'^organization/(?P<organization_id>[0-9]+)/dash/?$', views.organization_dash,name='organization_dash'),
    url(r'^organization/(?P<organization_id>[0-9]+)/?$', views.organization_detail,name='organization_detail'),
    url(r'^organization/create/?$', views.organization_create,name='organization_create'),
    url(r'^organization/(?P<organization_id>[0-9]+)/edit/?$', views.organization_settings,name='organization_settings'),
    #job urls
    url(r'^job/(?P<job_id>[0-9]+)/dash/?$', views.job_dash,name='job_dash'),
    url(r'^organization/(?P<organization_id>[0-9]+)/job/(?P<job_id>[0-9]+)/?$', views.jobrequest_dash,name='jobrequest_dash'),
    url(r'^job_creation$', views.job_creation,name='job_creation'),
    url(r'^job/(?P<job_id>[0-9]+)/edit/?$', views.job_settings,name='job_settings'),
    url(r'^job/status_update/$', views.job_status_update),
    url(r'^job/approve_update/$', views.job_approve_update), #when admin is made properly add this to javascript ajax 
    url(r'^job/job_delete/$', views.delete_job),
    #misc urls
    url(r'^$',views.front_page,name='front_page'),
    url(r'^search/?$',views.search,name='search'),
    url(r'^login/?$', views.login,name='login'),
    url(r'^logout/?$', logout,{'template_name':'main/logout.html'},name='logout'),
    url(r'^about/?$', views.about, name='about'),
    url(r'^quicksearch/?$', views.quicksearch,name='quicksearch'),
]

johnslist/main/models.py
from django.db import models
from django.forms import ModelForm,PasswordInput
from django.contrib.auth import forms
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_delete
from django.contrib.auth.models import User,Group
from guardian.shortcuts import assign_perm, remove_perm
from notifications.signals import notify
from django.core.urlresolvers import reverse

class UserProfile(models.Model):
    def __unicode__(self):
        return self.user.username

    # UserProfile - User
    user = models.OneToOneField(User,related_name = 'userprofile',null=True, blank = False)
    # purdueuser or communitypartner
    purdueuser = models.BooleanField(default=True, choices=((True, 'Purdue Professor'),(False, 'Community Organization')))
    # save which pages the user has visited before for the purposes of showing helpful dialogs
    visited_views = models.CharField(max_length=64,default="", null=True)
    first = models.CharField('firstname', max_length=128, null=True)
    last = models.CharField('lastname',max_length=128, null=True)
    organization = models.CharField('organization', max_length=128, null=True)
    title = models.CharField('title', max_length=128, null=True)
    phone = models.CharField('phone', max_length=128, null=True)


class CategoryGroup(models.Model):
    def __unicode__(self):
        return self.name

    name = models.CharField('Service Category Group Name',max_length=64)
    description = models.TextField('Service Category Group Description')

class Category(models.Model):
    def __unicode__(self):
        return self.name

    name = models.CharField('Service Category Name',max_length=64)
    description = models.TextField('Service Category Description',null=True)
    group = models.ForeignKey(CategoryGroup,related_name = 'categories')  # Category -= CategoryGroup

class Organization(models.Model):
    def __unicode__(self):
        return self.name

    name = models.CharField('Organization Name',max_length=64)
    description = models.TextField('Organization Description')
    categories = models.ManyToManyField(Category, related_name = 'organizations')  # Category =-= Organization
    group = models.OneToOneField(Group) # Organization - Group
    url = models.URLField('Website', default="http://", blank=True)
    phone_number = models.CharField('Organization phone number',max_length=64)
    icon = models.ImageField(upload_to='organization', null=True)
    available = models.BooleanField(default=True,choices=((True, "Accepting Jobs"),(False, "Not accepting Jobs")))

    class Meta:
        permissions = (
            ( 'view_organization','Can view Organization' ),
            ( 'edit_organization','Can edit Organization' ),
            ( 'is_admin', 'Is an Administrator')
            )

    # get list of jobs accepted for Org
    def jobrequests_accepted(self):
        return JobRequest.objects.filter(organization = self,accepted = True,completed = False)

    # get list of jobs applied to by Org
    def jobrequests_applied(self):
        return JobRequest.objects.filter(organization = self,accepted = False, applied = True)

    # get list of jobs pending for Org
    def jobrequests_pending(self):
        return JobRequest.objects.filter(organization = self,accepted = False,declined = False)

    # get list of jobs declined by Org
    def jobrequests_declined(self):
        return JobRequest.objects.filter(organization = self,accepted = False,declined = True)

    # get list of jobs completed by Org
    def jobrequests_completed(self):
        return JobRequest.objects.filter(organization = self,completed = True)

    # get admins of this org
    def get_admins(self):
        return [user for user in self.group.user_set.all() if user.has_perm('is_admin',self)]


@receiver(post_save, sender=Organization)
def add_perms_organization(sender,**kwargs):
    # check if this post_save signal was generated from a Model create (vs a Model edit)
    if 'created' in kwargs and kwargs['created']:
        organization=kwargs['instance']

        # allow organization to view and edit itself by default
        assign_perm('view_organization',organization.group,organization)
        assign_perm('edit_organization',organization.group,organization)

class Job(models.Model):
    def __unicode__(self):
        return self.name
    name = models.CharField('Job Name',max_length=128)
    # when the job was created
    date_created = models.DateTimeField('Date Created', auto_now=True)
    # what entity/organization needs this job?
    client_organization = models.CharField('What organization do you represent?', max_length=64)
    # short description
    description = models.TextField('Job Description', max_length=256)
    # end product to be delivered
    deliverable = models.TextField('Deliverable', max_length=256)
    # when Job is due for completion
    duedate = models.DateTimeField('Date Due')
    # all persons who may be affected by project
    #stakeholders = models.TextField('Stakeholders')
    # important technical requirements
    #additional_information = models.TextField('Additional Information', blank = True)
    # budget estimate
    #budget = models.CharField('Budget', max_length=64)
    # file attachments
    #attachments = models.FileField(upload_to='job', blank = True)
    creator = models.ForeignKey(User,related_name = 'jobs')
    organizations = models.ManyToManyField(Organization, through = 'JobRequest', blank=False, null=True)
    #organizations = models.CharField(default="nothing",null=True,max_length = 256)
    contact_information = models.CharField('Contact Information', max_length = 256, blank = False, null=True)
    skill_required = models.CharField('Volunteer skills required', max_length=256, blank = False, null=True)
    hours_day = models.CharField('Number of hours per day', max_length=256, blank = False, null=True)
    #  Job is closed after a jr is confirmed
    closed = models.BooleanField(default = False)
    # some tags to determine what organizations to submit job to
    categories = models.ManyToManyField(Category, related_name = 'jobs')
    #categories = models.CharField(default="nothing",null=True, max_length = 256)
    status = models.IntegerField(default = 0, choices = ((0, 'Pending'), (1, 'Approved'), (2, 'Disapproved'), (3, 'Closed')))
    active = models.BooleanField(default = True)
    approve = models.BooleanField(default = True) # add to admin side, already showing on community agency side
    #checkboxes 
    activism = models.BooleanField(default = False)
    arts = models.BooleanField(default = False)
    civil = models.BooleanField(default = False)
    school = models.BooleanField(default = False)
    crisis = models.BooleanField(default = False)
    criminal = models.BooleanField(default = False)
    disaster = models.BooleanField(default = False)
    economic = models.BooleanField(default = False)
    entrepreneurship = models.BooleanField(default = False)
    environment = models.BooleanField(default = False)
    food = models.BooleanField(default = False)
    housing = models.BooleanField(default = False)
    immigrants = models.BooleanField(default = False)
    individual = models.BooleanField(default = False)
    mental = models.BooleanField(default = False)
    poverty = models.BooleanField(default = False)
    substance = models.BooleanField(default = False)
    STEM = models.BooleanField(default = False)
    transportation = models.BooleanField(default = False)
    veterans = models.BooleanField(default = False)
    voting = models.BooleanField(default = False)
    other = models.CharField('Other categories', max_length=256, blank = True, null=True)
    class Meta:
        permissions = (
            ( 'view_job','Can view Job' ),
            ( 'edit_job','Can edit Job'),
            ( 'is_creator', 'Is a creator of Job')
            )

    # returns JobRequests that have been accepted
    def jobrequests_accepted(self):
        accepted = JobRequest.objects.filter(job = self, accepted = True)
        return accepted
    # returns JobRequests that have been applied to
    def jobrequests_applied(self):
        applied = JobRequest.objects.filter(job = self, accepted = False, applied = True)
        return applied
    # returns JobRequests that are pending
    def jobrequests_pending(self):
        pending = JobRequest.objects.filter(job = self, accepted = False, declined = False, completed = False)
        return pending
    # returns JobRequests that have been declined
    def jobrequests_declined(self):
        declined = JobRequest.objects.filter(job = self, declined = True)
        return declined
    # creates a new JobRequest
    def request_organization(self,organization):
        jr = JobRequest.objects.create(job = self,organization = organization);
        return jr

# add default job permissions
@receiver(post_save, sender=Job)
def add_perms_job(sender,**kwargs):
    # check if this post_save signal was generated from a Model create
    job=kwargs['instance']
    if 'created' in kwargs and kwargs['created']:

        # allow creator to view and edit job
        assign_perm('view_job',job.creator,job)
        assign_perm('edit_job',job.creator,job)
        # allow requested orgs to view job
        for org in job.organizations.all():
            assign_perm('view_job',org.group,job)
    else:
        # notify users of changed JobRequest
        if job.closed:
            jobrequests = job.jobrequests_accepted()
        else:
            jobrequests = job.jobrequests_accepted() | job.jobrequests_pending()
        for jobrequest in jobrequests:
            notify.send(job.creator,
                        verb="modified",
                        action_object=jobrequest,

johnslist/main/templates/main/main/about.html
{% extends "main/base.html" %}

{% block content %}

<h1><span class="text-muted">About </span>{{ SETTINGS.PROJECT_NAME }}</h1>
<h2><b>Purpose: </b></h2>
<p>
  This portal serves to facilitate the development of sustainable partnerships in service-learning between faculty, staff, students, and community partners. The portal does three things:
  <br><left><li>Allows community partners to share meaningful projects that will contribute to social and systemic change in the community.</li></left>
  <br><left><li>Connects community partners to faculty, staff, and students through service-learning courses.</li></left>
  <br><left><li>Provides faculty and staff with an opportunity to develop curricula that will match the need of community partners.</li></left>
</p>
<br>
<hr>
<h2><b>Features: </b></h2>
<p>
  As a Community partners, you can go onto our website and submit a project or service request that directly addresses a need for your organization. As a Faculty Member, you can see these requests, and connect your students to this Community partners through a service-learning course partnership. Additionally, the site administrator will monitor and facilitate these partnerships.
</p>
<br>
<hr>
<h2><b>Creators: </b></h2>
<p>
  This website was created by Purdue students in the Information Management Systems (IMS) sub-team of Engineering Projects in Community Service (EPICS) in partnership with the Office of Engagement and the United Way. For questions regarding the portal, please contact: Lindsey Payne, paynel@purdue.edu. For more information on EPICS and IMS, please visit:
</p>
<a href="http://epics.ecn.purdue.edu/ims/">epics.ecn.purdue.edu/ims/</a> 
<br>
<hr> 	

{% endblock content %}

johnslist/main/templates/main/main/agency_proposal_status.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

</body>
</html>

johnslist/main/templates/main/main/base.html
{% load staticfiles %}
{% load guardian_tags %}
{%load notifications_tags%}
{% load sniplates %}
{% load_widgets widgets="main/widgets.html" %}
<html>
    <head>
        <link rel='stylesheet' type='text/css' href="{% static 'bootstrap.min.css' %}"/>-->

        <link rel="icon" type="image/png" href='{% static 'favicon.png' %}'/>
        <script type='text/javascript' src="{% static 'jquery.min.js' %}"></script>
        <script type='text/javascript' src="{{ STATIC_URL }}js/Utilities.js"></script>
        <script type='text/javascript' src="{% static 'bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

        <link rel='stylesheet' type='text/css' href='{% static 'style.css' %}'/>

        <title>
            {{ SETTINGS.PROJECT_NAME }} - {%block title%}Connecting Jobs with Service Organizations{%endblock%}
        </title>
    </head>

    <body>
        {% block navbar %}
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">

                <!------------ NAVBAR ----->
                <div class="navbar-header">
                    <a  class="navbar-brand" rel="home" href="/" title="{{ SETTINGS.PROJECT_NAME }}">
                    <img draggable="false" style="max-width:27px;margin-top:-3px;margin-right:-7px;"
                            src='{% static 'brand.png' %}'>
                    </a>
                    <a href="{% url 'front_page' %}" class="navbar-brand">{{ SETTINGS.PROJECT_NAME }}</a>
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse" id="navbar-main">
                    <ul class="nav navbar-nav navbar-left">
                    <li><a href="{%url 'about'%}">About</a></li>
                    </ul>
                    <!--------- Logged in user navbar ------------>

                    {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'user_dash' %}"><i class="fa fa-dashboard"></i> Home</a></li>
                        <li><a href="{%url 'logout'%}"><i class="fa fa-sign-out"></i> Logout</a></li>
                    </ul>


                    <!--------- Anonymous user navbar ------------->

                    {% else %}
                    <ul class="nav navbar-nav navbar-right">

                    <li>
                        <p class="navbar-btn">
                        <a style="margin-right:5px;" href="{% url 'login' %}" class="btn btn-default">Login</a>
                        </p>
                    </li>
                    <li>
                        <p class="navbar-btn">
                        <a href="{% url 'user_create' "community" %}" class="btn btn-primary">Join</a>
                        </p>
                    </li>

                    </ul>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endblock navbar %}


        <br><br><br>
        <div class="container container-fluid">

        <!--------------- Form Messages ------------------->

        {% if form.errors %}
        <div id="error">
            <div class="alert alert-danger">

            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            There are incorrect fields.
            {{ form.errors }}
            </div>
        </div>
        {% endif %}

        <!--------------- Generic Message --------------->
        {% if messages %}
        <div>
            {% for message in messages %}
                {% if message.tags == 'info' %}
                <div class="confirm alert alert-dismissible alert-success">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    {{ message }}
                </div>
                {% elif message.tags == 'error' %}
                <div class="error alert alert-dismissible alert-danger">
                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    {{ message }}
                </div>
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}

        <!-------------- Main Page Content ------------------>

        {% block content %}
        {% endblock %}

        </div>

        <div class="footer">
        {% block footer %}
        <br><p>All Rights Reserved <a href="http://epics.ecn.purdue.edu/ims/">EPICS IMS 2015</a></p>
        {% endblock %}
        </div>

    </body>


</html>

johnslist/main/templates/main/main/communitypartner_dash.html
{% extends "main/base.html" %}
{% load template_tags %}

{% block content %}
{% if show_dialog %}
<div class="confirm alert alert-dismissible alert-info">
    <i type="button" class="close fa fa-close" data-dismiss="alert"></i>
    <h4> This page shows all notifications for jobs you have created.  Click the red 'Create Job' button below to begin creating a job.</h4>
</div>
{% endif %}

<div class="jumbotron">
  <center>
    <h3>{{ request.user }} <small>Dashboard</small></h3>
  </center>
</div>

<div class="form-group"><a href="{% url 'user_settings' %}"><button class="btn btn-info"><i class="fa fa-cog"></i> User Settings</button></a></div>

<div class="row">
  <div class="col-sm-6">
  {% dash_notifications "Notifications" unread_notifications read_notifications %}
  </div>

  <div class="col-sm-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Jobs
      </div>
      <div class="panel-body">
        <ul class="list-group">
          {% for job in jobs %}
          <a class="list-group-item" href="{% url 'job_dash' job.id %}">
            {{ job.name }}
          </a>
          {% endfor %}
          <br>
          <a href = '/job_creation' class="btn btn-danger"> <i class="fa fa-plus"></i> Create Job</a>
        </ul>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

johnslist/main/templates/main/main/job_create.html
{% extends "main/base.html" %}
{% block content %}
<div class="panel-heading">
  Create a job
</div>
<div class="jumbotron">

  {% if name %}<b>Job:{{ name }}.  Please check your email for a confirmation message.</b>
  {% else %}
  <div class="form-group">
    <form action="{% url 'job_create' %}" method="post">
      {% csrf_token %}

      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-bullhorn"></i>
        </span>
        <input class="form-control" type="text" name="name" placeholder="What is the job called?"></input>
      </div>

      <br/>

      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-coffee"></i>
        </span>
        <textarea class="form-control" name="description" placeholder="Describe what you need done."></textarea>
      </div>

      <br/>


      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-calendar"></i>
        </span>
        <input type="text" class="form-control" placeholder="mm/dd/yyyy Due date" name="duedate"></input>
      </div>

      <br/>
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-institution"></i>
        </span>

        {{form.organization}}

      </div>
      <br/>
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-check-circle-o"></i>
        </span>

        {{form.categories}}

      </div>
      <br>
      <input class="btn btn-primary" type="submit" value="Create Job">
    </form>


  </div>



  {% endif %}

</div>
{% endblock %}

johnslist/main/templates/main/main/job_settings.html
{% extends "main/base.html" %}
{% load widget_tweaks %}
{% load sniplates %}
{% load_widgets widgets="main/widgets.html" %}

{% block content %}

<div class="jumbotron">
  <center>
    <h3>{{ job.name }} <small>Settings</small></h3>
  </center>
</div>

<div class="form-group"><a href="{% url 'job_dash' job.id %}"><button class="btn btn-primary">Back</button></a></div>

<form action="{% url 'job_settings' job.id %}" method="post">
<h1>Basic information</h1>
  {% csrf_token %}

  <div class="row">

    <div class="col-sm-6">

      Project Title:
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-bullhorn"></i>
        </span>
        {% render_field form.name class+="form-control" %}
      </div>

      Community Organization & Project Coordinator:
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-coffee"></i>
        </span>
        {% render_field form.client_organization class+="form-control" %}
      </div>

       
						
      Contact Information: 
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-coffee"></i>
        </span>
      {% render_field form.contact_information class+="form-control" %}
       </div>
                        
      Briefly describe the product or service that you expect as a result of this project:
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-check"></i>
        </span>
        {% render_field form.deliverable class+="form-control" %}
      </div>

     Which categories would your project fit in the best:
                        <form action='url' method='post'> {% csrf_token %}
                            <br><input type="checkbox" name="activism" value="Yes" {% if job.activism %}checked{% endif %}>Activism & advocacy
                            <br><input type="checkbox" name="arts" value="Yes" {% if job.arts %}checked{% endif %}>Arts & culture
                            <br><input type="checkbox" name="civil" value="Yes" {% if job.civil %}checked{% endif %}>Civil rights & human rights
                            <br><input type="checkbox" name="school" value="Yes" {% if job.school %}checked{% endif %}>School readiness in Pre-K to 12 education
                            <br><input type="checkbox" name="crisis" value="Yes" {% if job.crisis %}checked{% endif %}>Crisis & conflict resolution  
                            <br><input type="checkbox" name="criminal" value="Yes" {% if job.criminal %}checked{% endif %}>Criminal justice & legal representation
                            <br><input type="checkbox" name="disaster" value="Yes" {% if job.disaster %}checked{% endif %}>Disaster preparedness
                            <br><input type="checkbox" name="economic" value="Yes" {% if job.economic %}checked{% endif %}>Economic development
                            <br><input type="checkbox" name="entrepreneurship" value="Yes" {% if job.entrepreneurship %}checked{% endif %}>Entrepreneurship
                            <br><input type="checkbox" name="environment" value="Yes" {% if job.environment %}checked{% endif %}>Environment & sustainability
                            <br><input type="checkbox" name="food" value="Yes" {% if job.food %}checked{% endif %}>Food security
                            <br><input type="checkbox" name="housing" value="Yes" {% if job.housing %}checked{% endif %}>Housing & homelessness
                            <br><input type="checkbox" name="immigrants" value="Yes" {% if job.immigrants %}checked{% endif %}>Immigrants & migrant worker rights
                            <br><input type="checkbox" name="individual" value="Yes" {% if job.individual %}checked{% endif %}>Individual & community health
                            <br><input type="checkbox" name="mental" value="Yes" {% if job.mental %}checked{% endif %}>Mental health
                            <br><input type="checkbox" name="poverty" value="Yes" {% if job.poverty %}checked{% endif %}>Poverty alleviation
                            <br><input type="checkbox" name="substance" value="Yes" {% if job.substance %}checked{% endif %}>Substance abuse & recovery
                            <br><input type="checkbox" name="STEM" value="Yes" {% if job.STEM %}checked{% endif %}>STEM education
                            <br><input type="checkbox" name="transportation" value="Yes" {% if job.transportation %}checked{% endif %}>Transportation
                            <br><input type="checkbox" name="veterans" value="Yes" {% if job.veterans %}checked{% endif %}>Veterans
                            <br><input type="checkbox" name="voting" value="Yes" {% if job.voting %}checked{% endif %}>Voting
                            <br>Other. Please specify:<div class="input-group"><span class="input-group-addon"><i class="fa fa-coffee"></i></span>{% render_field form.other class+="form-control" placeholder="Technology" %} </div>
                        </form>

      <h1>Student requirements information</h1>



      Specify the student skill sets required: 
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-coffee"></i>
        </span>
        {% render_field form.skill_required class+="form-control" %}
      </div>


      Specify the date when this project is due. If you are not sure of the exact date, give a close approximation:
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-calendar"></i>
        </span>
        {% render_field form.duedate class+="form-control" %}
      </div>
      
      Specify the number of hours the student needs to work per day/week: <br>
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-coffee"></i>
        </span>
        {% render_field form.hours_day class+="form-control" %}
      </div>
       
      Give a short description of the duties of a student:
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-coffee"></i>
        </span>
        {% render_field form.description class+="form-control" %}
      </div>

        <div class="hide">
        {% render_field form.active class+="form-control" %}
         {% render_field form.approve class+="form-control" %}
         </div>

      <!--Stakeholders
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-coffee"></i>
        </span>
        {% render_field form.stakeholders class+="form-control" %}
      </div>

      Budget
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-money"></i>
        </span>
        {% render_field form.budget class+="form-control" %}
      </div>

      Attachments
      <div class="input-group">
        <span class="input-group-addon">
          <i class="fa fa-file"></i>
        </span>
        {% render_field form.attachments class+="form-control" %}
      </div>

      <div class="panel-group">
          {% render_field form.categories class+="form-control" %}

      </div>

      <div class="panel-group">
          {% render_field form.categories class+="form-control" %}
    </div>

  </div>-->

  <div class="form-group pull-right">
    <input class="btn btn-primary" type="submit" value="Save Changes" onclick="submitFunction()">
  </div>
</form>
<!--script>
  $('#id_categories').val({{ categories_id }});
</script-->   

{% endblock content %}

johnslist/main/templates/main/main/organization_detail.html
{% extends "main/base.html" %}
{% block content %}
<div class="jumbotron">
    <center>

      <img src="{{organization.icon.url}}" name="aboutme" height="140">
      <h3>
        {%if organization.available %}
        <span class="badge success"><i class="fa fa-check"></i> Available</span>
        {%else%}
        <span class="badge danger"><i class="fa fa-remove"></i> Not Available</span>
        {%endif%}
        <br>
        {{organization.name}}
      </h3>

      {% for category in organization.categories.all %}
      <a href="{% url 'search' %}?search={{ category.name }}&search_model=organization&search_by=category" class="btn btn-default">{{category.name}}</a>
      {%endfor%}

    </center>
</div>
<div class="row">
  <div class="col-sm-3">

    {% if organization.url %}
    <div class="panel"><a href="{{ organization.url }}" target="_blank">
            <button class="btn btn-primary btn-block">
                <i class="fa fa-external-link"></i> Organization's Website
            </button>
    </a></div>
    {% endif %}

    <div class="panel panel-default">
      <div class="panel-heading">Stats</div>
      <ul class="list-group">
        <li class="list-group-item text-right"><span class="pull-left"><strong class="">Members</strong></span> {{members|length}}</li>
        <li class="list-group-item text-right">
          <span class="pull-left"><strong class="">Joined</strong></span>2015
        </li>
      </ul>
    </div>

  </div>

  <div class="col-sm-9" style="" contenteditable="false">
    <div class="panel panel-default">
      <div class="panel-heading">Description</div>
      <div class="panel-body">
        {{organization.description}}
      </div>
    </div>
  </div>
</div>

{% endblock content%}

johnslist/main/templates/main/main/user_job_index.html
{% extends "main/base.html" %}
{% block content %}
<u>Jobs you have created</u><br>
{% for job in jobs.all %}
<a href = "{%url 'job_dash' job.id%}">{{job}}</a>
{% endfor %}
{% endblock content %}